Algoritmo "MULTIPLICAÇão"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/08/2024
Var
 num1, num2, resultado: Inteiro;


Inicio
 Escreva ("Digite o primeiro numero")
 Leia (num1)
 Escreva ("Digite o segundo")
 Leia (num2)
  resultado <- (num1 + num2) * 3
  Escreva ("o resultado final é:" , resultado)


Fimalgoritmo