Algoritmo "Real INTEIRO"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/08/2024
Var
 num1: Inteiro;
 num2, Resultado: Real;


Inicio
Escreva ("bote o numero")
Leia (num1)
Escreva ("bote o numero")
Leia (num2)
  Resultado <- (num1 + num2)
  Escreva (" o Resultado é:" , Resultado)


Fimalgoritmo