Algoritmo "Real"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/08/2024
Var
 Num1, Num2, Resultado: Real;


Inicio
  Escreva (" Digite o Primeiro Numero")
  Leia (Num1)
  Escreva (" Digite o Segundo")
  Leia (Num2)
  Resultado <- (Num1 + Num2)
  Escreva (" o Resultado é:" , Resultado)


Fimalgoritmo