Algoritmo "SUBITRAÇÃO"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/08/2024
Var
  num1, num2, Resultado: inteiro;


Inicio
Escreva (" Digite um numero")
leia (num1)
Escreva (" Digite um numero")
Leia (num2)
 Resultado <- (num1 - num2)
 Escreva (" O Resultado é:" , Resultado)



Fimalgoritmo